### ISSUE TITLE
UnboundLocalError: local variable 'move_event_end' referenced before assignment

### ISSUE THREAD

**Issue by batara666** [beuaaa/pywinauto_recorder#37]
UnboundLocalError: local variable 'move_event_end' referenced before assignment

Windows 11
pywinauto recorder 0.5.1

**Comment by beuaaa** [comment]
Hi @batara666,

I have not yet tested Pywinauto Recorder with Windows 11. I won't do it right away but I'll keep you posted.

**Comment by batara666** [comment]
wow, thanks for the reply

so, this error happen when I just stop the recording without waiting yellow rectangle to show up

**Comment by luisaoisdead** [comment]
Hello i solved downloading the main source code and in conda type "pip setup.py install " in the source folder.

**Comment by cgmike** [comment]
Happens to me as well on Windows 10 with Pywinauto_recorder 0.5.1:
```
`Traceback (most recent call last):
  File "U:\Develop\PYWINA~1\keyboard\_generic.py", line 22, in invoke_handlers
  File "U:\Develop\PYWINA~1\pywinauto_recorder\recorder.py", line 668, in __key_on
  File "U:\Develop\PYWINA~1\pywinauto_recorder\recorder.py", line 1139, in stop_recording
  File "U:\Develop\PYWINA~1\pywinauto_recorder\recorder.py", line 201, in process_events
  File "U:\Develop\PYWINA~1\pywinauto_recorder\recorder.py", line 294, in process_drag_and_drop_or_click_events
UnboundLocalError: local variable 'move_event_end' referenced before assignment`


```

**Comment by beuaaa** [comment]
Hi @cgmike,

Pywinauto Recorder 0.6.0 (compiled version and source) is about to be released, it could fix it.

**Comment by beuaaa** [comment]
I tried Pywinauto Recorder 0.6.1 with Windows 11 in a virtual machine and 'vcruntime140.dll' was missing. I had to add it manually then it worked.
Was it the same for you?
