### ISSUE TITLE
match_entry_list exception: list index out of range

### ISSUE THREAD

**Issue by pleabargain** [beuaaa/pywinauto_recorder#53]
I know that the app will not work on all WIN 11 machines. When I try to replay a script I get the following.

```Reading configuration file: C:\Users\Dennis Daniels\Pywinauto recorder\config.ini
Window filtering mode: ignore_windows
Ignored windows: []
COMPTYPES CACHE FOLDER: C:\Users\DENNIS~1\AppData\Local\Temp\comtypes_cache\pywinauto_recorder-38
PYWINAUTO RECORDER FOLDER: C:\Users\Dennis Daniels\AppData\Local\Programs\Pywinauto recorder\pywinauto_recorder
Your Pywinauto recorder is up to date.
match_entry_list exception: list index out of range
match_entry_list exception: list index out of range
match_entry_list exception: list index out of range
Traceback (most recent call last):
  File "C:\Users\DENNIS~1\AppData\Local\Programs\PYWINA~1\pywinauto_recorder\core.py", line 50, in get_wrapper_path
TypeError: can only concatenate str (not "NoneType") to str
['Traceback (most recent call last):\n', '  File "C:\\Users\\DENNIS~1\\AppData\\Local\\Programs\\PYWINA~1\\pywinauto_recorder\\core.py", line 50, in get_wrapper_path\n', 'TypeError: can only concatenate str (not "NoneType") to str\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\DENNIS~1\\AppData\\Local\\Programs\\PYWINA~1\\pywinauto_recorder\\recorder.py", line 935, in run\n', '  File "C:\\Users\\DENNIS~1\\AppData\\Local\\Programs\\PYWINA~1\\pywinauto_recorder\\cor
[recorded Wed Aug 31 15_22_00 2022.txt]e.py", line 55, in get_wrapper_path\n', "AttributeError: 'TypeError' object has no attribute 'message'\n"]
Warning: No window 'https://edition.cnn.com - Google Chrome' with control type 'Pane' found!
match_entry_list exception: list index out of range
match_entry_list exception: list index out of range
command--->
Recording in file: C:\Users\Dennis Daniels\Pywinauto recorder\recorded Wed Aug 31 15_22_00 2022.py
<---command
command--->
<---command
```

Attached is the .py file that was created.
(https://github.com/beuaaa/pywinauto_recorder/files/9461104/recorded.Wed.Aug.31.15_22_00.2022.txt)

**Comment by beuaaa** [comment]
Hello @pleabargain,

Could you send me the error messages displayed in the console when replaying 'recorded Wed Aug 31 15_22_00 2022.py'?

**Comment by InstanceGaming** [comment]
While I don't have the time to fully explore this issue to fix it right now, I have pin-pointed the source of the bug: a off-by-one indexing error in `match_entry_sequence(i_e, entry_list, sequence_list)` in `core.py`. For my own hotfix, rewriting the function to the following allows it to run without the error, however more investigation will be needed to find out why `i_s` sometimes allows invalid indexes of `entry_list` when called by `match_entry_list(entry_list, template_list)`. I did try `range(len(sequence_list) - n)` (with n=1 or 2) but that didn't seem to help. Hope this helps a bit.

```
        el_end = len(entry_list) - 1
	for i_s in range(len(sequence_list)):
		if i_s > el_end:
			i_s = el_end
		entry_list_item = entry_list[i_e + i_s]
		seq_list_item = sequence_list[i_s]
		if not match_entry(entry_list_item, seq_list_item):
			return False
	return True
```

**Comment by pleabargain** [comment]
Thank you for taking the time to respond ☺️

**Comment by beuaaa** [comment]
@InstanceGaming Could you give me the input parameters of the 'match_entry_list' function that cause the error so that I can investigate?

**Comment by InstanceGaming** [comment]
```
Release 0.6.3

Stacktrace:
run in recorder.py:950
find_element in core.py:432
match_entry_list in core.py:236
	Scope state at time of exception:
		entry_list = ['C:\\Users\\User\\Downloads\\somefile.txt||Window', '||Pane']
		i_e = 0
		idx_list = []
		res = [['C:\\Users\\User\\Downloads\\somefile.txt||Window', '||Pane', '||Pane']]
		size = 3
		template_list = ['C:\\Users\\User\\Downloads\\somefile.txt||Window', '||Pane', '||Pane']
match_entry_sequence in core.py:188
	Scope state at time of exception:
		entry_list = ['C:\\Users\\User\\Downloads\\somefile.txt||Window', '||Pane']
		i_e = 0
		i_s = 2
		sequence_list = ['C:\\Users\\User\\Downloads\\somefile.txt||Window', '||Pane', '||Pane']
```

**Comment by beuaaa** [comment]
The fixed code is:


```python
	if (i_e + len(sequence_list)) > len(entry_list):
		return False
	for i_s in range(len(sequence_list)):
		if not match_entry(entry_list[i_e + i_s], sequence_list[i_s]):
			return False
	return True
```
I'm going to push the code.
